### ISSUE TITLE
Pouvoir mettre plusieurs espaces à la suite

### ISSUE THREAD

**Issue by vengil5** [jper1679/zc_card_generator#17]
Bonjour,
Il n'est pas possible de mettre plusieurs espaces à la suite. L'intérêt est de pouvoir décaler la description d'une carte pour que le texte ne soit pas caché pas la cloche (de l’icône arme bruyante, ou arme non bruyante).

Merci pour ton super utilitaire !

**Comment by jper1679** [comment]
C'est fait.
